name: BSD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating_system: [ freebsd, netbsd, openbsd ]
        architecture: [ arm64, x86-64 ]
        include:
          - operating_system: freebsd
            version: '14.2'
            pkginstall: sudo pkg update && sudo pkg install -y cmake git ninja pkgconf
          - operating_system: netbsd
            version: '10.1'
            pkginstall: sudo pkgin update && sudo pkgin -y install clang cmake git ninja-build pkgconf
          - operating_system: openbsd
            version: '7.7'
            pkginstall: sudo pkg_add -u && sudo pkg_add cmake git ninja pkgconf

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: cross-platform-actions/action@v0.28.0
        with:
          operating_system: ${{ matrix.operating_system }}
          architecture: ${{ matrix.architecture }}
          version: ${{ matrix.version }}
          run: |
            ${{ matrix.pkginstall }}
            cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
            cmake --build build --config Release
